<div class="coupon">
    <div class="coupon__img">
        {if $listing.shop_image}
            <a href="{$smarty.const.IA_URL}shop/{$listing.title_alias}.html">
                {ia_image file=$listing.shop_image type='thumbnail' title=$listing.title|escape:'html' class='img-responsive'}
            </a>
        {else}
            <a href="{$smarty.const.IA_URL}shop/{$listing.title_alias}.html" class="pull-left ia-item-thumbnail">
                <img src="http://free.pagepeeker.com/v2/thumbs.php?size=m&url={$listing.website|escape:url}" alt="Generated by pageppeker.com" class="img-responsive">
            </a>
        {/if}
    </div>
    <div class="coupon__body">
        <div class="coupon__title">{ia_url type='link' item='shops' data=$listing text=$listing.title}</div>
        <div class="coupon__desc">
            {$listing.description|strip_tags|truncate:250:'...'}
        </div>
        <div class="coupon__shop">
            <span><span class="fa fa-tags"></span> {lang key='coupons'}: {$listing.num_coupons}</span>
        </div>
    </div>
</div>