<div class="shop-page">
	{if $shop.shop_image}
		<div class="shop-page__image">
			{ia_image file=$shop.shop_image type='thumbnail' title=$shop.title}
		</div>
	{else}
		<div class="shop-page__image-screen">
			<img src="http://free.pagepeeker.com/v2/thumbs.php?size=m&url={$shop.website|escape:url}" alt="Generated by pagepeeker.com">
		</div>
	{/if}

	<div class="shop-page__title">
		<h1>{$shop.title}</h1>
		<p>
			{if $shop.affiliate_link && 'http://' != $shop.affiliate_link}
				<a href="{$shop.affiliate_link}" target="_blank">{$shop.website}</a>
			{else}
				<a href="{$shop.website}" target="_blank">{$shop.website}</a>
			{/if}
		</p>
	</div>

	{if $shop.description}
		<div class="shop-page__desc">{$shop.description}</div>
	{/if}

	{ia_hooker name='smartyViewListingBeforeFooter'}

	<div class="shop-page__coupons">
		<ul class="nav nav-tabs nav-tabs-nice">
			<li{if !isset($smarty.get.sorting) || (isset($smarty.get.sorting) && 'all' == $smarty.get.sorting)} class="active"{/if}><a href="{$smarty.const.IA_SELF}?sorting=all">{lang key='all_coupons'}</a></li>
			<li{if isset($smarty.get.sorting) && 'active' == $smarty.get.sorting} class="active"{/if}><a href="{$smarty.const.IA_SELF}?sorting=active">{lang key='active_coupons'}</a></li>
			<li{if isset($smarty.get.sorting) && 'expired' == $smarty.get.sorting} class="active"{/if}><a href="{$smarty.const.IA_SELF}?sorting=expired">{lang key='expired_coupons'}</a></li>
			<li class="nav-tabs-nice__info">
				{lang key='coupons'}: {$couponsNum}
			</li>
		</ul>

		{if $coupons}
			{foreach $coupons as $listing}
				{include file='extra:coupons/list-coupons'}
			{/foreach}
		{/if}

		{if $coupons_expired}
			{foreach $coupons_expired as $listing}
				{include file='extra:coupons/list-coupons'}
			{/foreach}
		{/if}
	</div>
</div>