<div class="shop-page">
    {if $item.shop_image}
        <div class="shop-page__image">
            {ia_image file=$item.shop_image type='thumbnail' title=$item.title class='img-responsive'}
        </div>
    {else}
        <div class="shop-page__image-screen">
            <img src="//free.pagepeeker.com/v2/thumbs.php?size=m&url={$item.website|escape:url}" alt="Generated by pagepeeker.com">
        </div>
    {/if}

    <div class="shop-page__title">
        <h1>{$item.title}</h1>
        <p>
            {if $item.affiliate_link && 'http://' != $item.affiliate_link}
                <a href="{$item.affiliate_link}" target="_blank">{$item.website}</a>
            {else}
                <a href="{$item.website}" target="_blank">{$item.website}</a>
            {/if}
        </p>
    </div>

    {if $item.description}
        <div class="shop-page__desc">{$item.description}</div>
    {/if}

    {ia_hooker name='smartyItemViewBeforeTabs'}

    {include 'item-view-tabs.tpl' isView=true exceptions=['title', 'affiliate_link', 'website', 'description'] class='ia-item-view-tabs'}

    {ia_hooker name='smartyViewListingBeforeFooter'}

    <div class="shop-page__coupons">
        <ul class="nav nav-tabs nav-tabs-nice">
            <li{if !isset($smarty.get.sorting) || (isset($smarty.get.sorting) && 'all' == $smarty.get.sorting)} class="active"{/if}><a href="{$smarty.const.IA_SELF}?sorting=all">{lang key='all_coupons'}</a></li>
            <li{if isset($smarty.get.sorting) && 'active' == $smarty.get.sorting} class="active"{/if}><a href="{$smarty.const.IA_SELF}?sorting=active">{lang key='active_coupons'}</a></li>
            <li{if isset($smarty.get.sorting) && 'expired' == $smarty.get.sorting} class="active"{/if}><a href="{$smarty.const.IA_SELF}?sorting=expired">{lang key='expired_coupons'}</a></li>
            <li class="nav-tabs-nice__info">
                {lang key='coupons'}: {$couponsNum}
            </li>
        </ul>

        {if $coupons}
            {foreach $coupons as $listing}
                {include file='extra:coupons/list-coupons'}
            {/foreach}
        {/if}

        {if $coupons_expired}
            {foreach $coupons_expired as $listing}
                {include file='extra:coupons/list-coupons'}
            {/foreach}
        {/if}
    </div>
</div>